### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by alexanderadam** [tarleb/zeitmail#1]
Hi @tarleb,

I just wanted to **thank you**. I found zeitmail just by accident and hope I can try it in the following weeks.
It looks really awesome as far as I can see!

I just had a first glance on it. Is it correct that [Z-Push](https://wiki.z-hub.io/display/ZP/Installation) and [Autoconfig](https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Autoconfiguration) things aren't integrated (yet)? If so: am I allowed to create some issues for them?

Do you think it's possible to get compatibility to Ubuntu 16.04 LTS?

I saw you still have some [open branches](https://github.com/tarleb/zeitmail/branches). Anything I could help you (or at least try to as SaltStack is completely new to me)?

Have a nice week,
Alex

PS: How do you think about using [rainloop](https://www.rainloop.net/) instead roundcube?

**Comment by tarleb** [comment]
Hello Alex,

Thank you for your message! The prospect of zeitmail being useful to somebody makes me quite happy.

I didn't know about Z-Push, looks interesting.  You are correct that autoconfig hasn't been implemented yet, that's always been on my todo list.

I'll happily help were I can, but I should note that the project is currently dormant as I'm not managing any servers right now. My priorities lie with other projects at the moment and the amount of support I can give will be limited for that reason.

Getting compatibility with Ubuntu LTS should be a matter of changing `salt/roots/apt/init.sls`. It might even be enough to remove *apt* from `salt/roots/top.sls`, but I'm not sure.

The open branches just haven't been cleaned up, most of them have been merged into master.

On the topic of rainloop vs. roundcube: I chose roundcube because it is very well tested and used in production by big companies like posteo.  Rainloop is beautiful and very easy to use, but I chose security over style and went with roundcube due to its proven track record[1].

Hope this helps,

Albert

[1]: there have been [exceptions](https://roundcube.net/news/2016/04/20/updates-1.1.5-and-1.0.9-published)

**Comment by alexanderadam** [comment]
@tarleb thank you for the fast response. Okay, in that case I will create Z-Push and autoconfig issues (no pressure here) and will try Ubuntu LTS.

PS: Indeed there have been [exceptions](https://www.heise.de/security/meldung/Kritische-Luecke-in-Roundcube-Mail-hackt-Server-3566864.html). I strongly doubt that roundcube is more secure just because it's used by big companies. Flash and Java-Browser-Plugins were used by big companies as well… 😉
